### ISSUE TITLE
where is the module named 'models_kuangliu'?

### ISSUE THREAD

**Issue by UncleshoesXR** [tianshuocong/TePA#1]
There is a module named 'models_kuangliu' in almost every experiment?But there are no tips about how to get it?.
Details follows:
          Traceback (most recent call last):
            File "DUA/poison_dua.py", line 17, in <module>
              from models_kuangliu import *
          ModuleNotFoundError: No module named 'models_kuangliu'

**Comment by tianshuocong** [comment]
Hi!

The architecture of the surrogate model is saved in `models_kuangliu`, now I rename it with `models_surrogate`, by using `from models_surrogate import *` you can load the checkpoint of the surrogate model.

Thanks for your kind reminder!
