### ISSUE TITLE
Code issues for poison_tent.py

### ISSUE THREAD

**Issue by oppurity12** [tianshuocong/TePA#3]
Hi, thanks for your fascinating work!

I am running poison_tent.py. However, vgg and norm file does not exist in current version.  
If you upload the updated code, I would greatly appreciate it.

Looking forward your reply!

Best,
Jeongyeon Hwang.

**Comment by tianshuocong** [comment]
Hi! Thanks for your interest in our work.
I just upload `vgg.py` and `norm.py` files, pls check them!

Best wishes.
