### ISSUE TITLE
code issues for tent and rpl

### ISSUE THREAD

**Issue by zhangansen** [tianshuocong/TePA#4]
Hi

When I run rpl and tent, I get the following errors 
CfgNode is immutable.

In the code I commented out cfg.freeze() and it doesn't report an error, what went wrong here please?
cfg.LOG_TIME, cfg.LOG_DEST = current_time, log_dest
cfg.freeze()

Thanks!

**Comment by tianshuocong** [comment]
Hi! I am so sorry that I cannot reproduce your bug. Have you installed the [requirement](https://github.com/DequanWang/tent/blob/master/requirements.txt) for running TENT? By the way, the config file only controls the hyperparameters, and hyperparameters can also be set directly in the main code without using config.

**Comment by zhangansen** [comment]
Yes, I think I installed the required fittings.
I think it was Tent's utility.py running eval_base() that used load_cfg_fom_args() when freezing the cfg, and then when running load_cfg_fom_args() again during eval_online() made a modification to the property of the cfg (log_time ), but since it was frozen, I couldn't make the change and got an error.
Please let me know if I misunderstood somewhere, thanks!

**Comment by zhangansen** [comment]
Yes, I think I installed the required fittings.
I think it was Tent's utility.py running eval_base() that used load_cfg_fom_args() when freezing the cfg, and then when running load_cfg_fom_args() again during eval_online() made a modification to the property of the cfg (log_time ), but since it was frozen, it couldn't make the change and got an error.
Please let me know if I misunderstood somewhere, thanks!

**Comment by tianshuocong** [comment]
Hi, You indeed find out the reason! When run `eval_online()`, we should annotate the code as `#eval_base()`, thanks for your correction :)

**Comment by zhangansen** [comment]
Thanks! By the way，Can you share the code for the DEFENSE section please, thanks!

**Comment by tianshuocong** [comment]
Sure, you can find JPEG, BDR, and R&P [here](https://github.com/tianshuocong/TePA/blob/main/TTT/defense.py), and adversarial training is shown in Alg.2 in our paper.
